### ISSUE TITLE
Bug: TypeError: get_cached_credentials() missing required argument 'log' causes background thread crash and 403s (v0.1.96, v0.1.97)

### ISSUE THREAD

**Issue by tempus-omarsalka** [GoogleCloudDataproc/dataproc-jupyter-plugin#451]
### Describe the bug
In versions `0.1.96` and `0.1.97`, and possibly other versions, the background thread responsible for caching/refreshing credentials crashes immediately due to a missing `log` argument when calling `get_cached_credentials()`. 

Because the thread dies, the plugin loses its ability to fetch credentials. This cascades into `403 Forbidden` errors when the plugin tries to communicate with Google Cloud Storage to retrieve Dataproc Serverless Session Templates, ultimately breaking the JupyterLab UI for our users and interrupting active scripts.

### Steps to reproduce
1. Install `dataproc-jupyter-plugin` version `0.1.96` or `0.1.97` (Python 3.13).
2. Launch JupyterLab.
3. Observe the Jupyter server logs as the plugin attempts to initialize and cache credentials.
4. The background thread crashes, and subsequent plugin requests to GCP return 403s.

### Expected behavior
The `get_cached_credentials` function should execute successfully in the background thread without raising a `TypeError`, allowing the plugin to maintain active credentials and retrieve session templates.

### Server Logs / Stack Trace
Here is the exact traceback from our Jupyter server logs showing the thread crash:

```text
Exception in thread Thread-127 (get_cached_credentials):
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/threading.py", line 1044, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.13/threading.py", line 995, in run
    self._target(*self._args, **self._kwargs)
TypeError: get_cached_credentials() missing 1 required positional argument: 'log'
```

Immediately followed by the plugin failing to retrieve templates due to the missing credentials:

```text
[I 2026-08-31 12:40:04.829 ServerApp.DataprocPluginClient] GET https://storage.googleapis.com/storage/v1/b?project=<project_id>&prefix= 403
```
### Environment details:
* Plugin version: 0.1.96 and 0.1.97
* Python version: 3.13
* Platform: GKE-hosted JupyterHub

**Comment by tempus-omarsalka** [comment]
This is no longer an issue. We're pinning jupyterlab to v3.6, which led to pip automatically installing version 0.1.70 and not the latest "0.1.97". dataproc-jupyter-plugin v0.1.70 has this bug. We mistakenly thought we were using the latest version "0.1.97" and tried pinning the version to v0.1.96. Somehow we never ended up deploying the docker image that has this pinned version and mistakenly kept using the other version that had dataproc-jupyter-plugin v0.1.70.

Can confirm now everything is working fine using v0.1.96 and i'm sure the same will be true for v0.1.97. Thanks and sorry for the confusion.
